name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Cache dependecies
        uses: actions/cache@3
        with:
          path: ~/.npm
          key: deps-naode-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest

    outputs:
      wohooscript: ${{ steps.publish.outputs.wohooscript }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Cache dependecies
        uses: actions/cache@3
        with:
          path: ~/.npm
          key: deps-naode-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Publish JS filename
        id: publish
        run: |
          SCRIPT_FILE=$(basename dist/assets/*.js)
          echo "wohooscript=$SCRIPT_FILE" >> "$GITHUB_OUTPUT"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Show downloaded files
        run: ls -R

      - name: Output script filename
        run: echo "${{ needs.build.outputs.wohooscript }}"

      - name: Deploy
        run: echo "Deploying ${{ needs.build.outputs.wohooscript }}"